---

# - name: Install dependencies deb
#   package: name="{{item}}" state=present
#   with_items: "{{python_dependencies}}"

- name: Install python-pycurl
  package: name=python-pycurl state=present

# - name: Add python apt repository
#   apt_repository: repo=no update_cache=yes
#   when: python_ppa != False and python_ppa != ""

- name: Install python
  package: name=python-{{item}} state=present
  with_items: "{{ python_versions }}"